name: Template generation

on: [push]


jobs:
  template-gen:
    if: ${{ github.repository != 'aris-space/hermes-PCB-project-template' && github.run_number == 1 }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Rename files
      env: 
        REPO_NAME: ${{ github.repository }}
      run: python3 .github/workflows/template_rename.py $REPO_NAME
      
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Generate project from template"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
